-- changelog number: 3
-- Antinie Radu creates table 'GAME'
show variables like 'lower_case_table_names';
CREATE TABLE IF NOT EXISTS game (
  ID   INT(10) PRIMARY KEY AUTO_INCREMENT,
  name varchar(5000),
  minimum_number_of_players int,
  maximum_number_of_players int,
  suggested_age int,
  average_playing_time int,
  description varchar(10000),
  image_link varchar(10000)
);

INSERT INTO `game` (`ID`, `name`, `minimum_number_of_players`, `maximum_number_of_players`, `suggested_age`, `average_playing_time`, `description`, `image_link`)
VALUES (1, "COSMIC ENCOUNTER", 3, 5, 7, 60, ". COSMIC ENCOUNTER is a brilliant mix of genuine strategy and unpredictable hilarity", "https://cf.geekdo-images.com/opengraph/img/aSPoR14lqt1IWmeuSzgSpK6IQL8=/fit-in/1200x630/pic4243113.jpg");
INSERT INTO `game` (`ID`, `name`, `minimum_number_of_players`, `maximum_number_of_players`, `suggested_age`, `average_playing_time`, `description`, `image_link`)
VALUES (2, "SPLENDOR", 2, 4, 10, 40, "For a small and light board game that contains enough strategy to play over and over, while also not being intimidating to new players, Splendor is the ideal option. ", "https://cf.geekdo-images.com/opengraph/img/9ZQ1bKSqxPFhRn9MF01Wwf-wgPA=/fit-in/1200x630/pic1904079.jpg");
INSERT INTO `game` (`ID`, `name`, `minimum_number_of_players`, `maximum_number_of_players`, `suggested_age`, `average_playing_time`, `description`, `image_link`)
VALUES (3, "PANDEMIC LEGACY: SEASON 1", 2, 4, 13, 75, "Pandemic Legacy is a co-operative campaign game, with an overarching story-arc played through 12-24 sessions, depending on how well your group does at the game. At the beginning, the game starts very similar to basic Pandemic, in which your team of disease-fighting specialists races against the clock to travel around the world, treating disease hotspots while researching cures for each of four plagues before they get out of hand. During a player''s turn, they have four actions available, with which they may travel around in the world in various ways (sometimes needing to discard a card), build structures like research stations, treat diseases (removing one cube from the board; if all cubes of a color have been removed, the disease has been eradicated), trade cards with other players, or find a cure for a disease (requiring five cards of the same color to be discarded while at a research station). Each player has a unique role with special abilities to help them at these actions. After a player has taken their actions, they draw two cards. These cards can include epidemic cards, which will place new disease cubes on the board, and can lead to an outbreak, spreading disease cubes even further. Outbreaks additionally increase the panic level of a city, making that city more expensive to travel to.Each month in the game, you have two chances to achieve that month''s objectives. If you succeed, you win and immediately move on to the next month. If you fail, you have a second chance, with more funding for beneficial event cards. During the campaign, new rules and components will be introduced. These will sometimes require you to permanently alter the components of the game; this includes writing on cards, ripping up cards, and placing permanent stickers on components. Your characters can gain new skills, or detrimental effects. A character can even be lost entirely, at which point it''s no longer available for play.", "https://images-na.ssl-images-amazon.com/images/I/61RUJVWvf9L._AC_.jpg");
INSERT INTO `game` (`ID`, `name`, `minimum_number_of_players`, `maximum_number_of_players`, `suggested_age`, `average_playing_time`, `description`, `image_link`)
VALUES (4, "QUACKS OF QUEDLINBURG", 2, 4, 10, 50, "In The Quacks of Quedlinburg, players are charlatans — or quack doctors — each making their own secret brew by adding ingredients one at a time. Take care with what you add, though, for a pinch too much of this or that will spoil the whole mixture!
Each player has their own bag of ingredient chips. During each round, they simultaneously draw chips and add them to their pot. The higher the face value of the drawn chip, the further it is placed in the swirling pattern. Push your luck as far as you can, but if you add too many cherry bombs, your pot explodes!
At the end of each round, players gain victory points and coins to spend on new ingredients to add to their bags, depending on the strength of the ingredients in their pots. But players with exploded pots must choose points or coins — not both! The player with the most victory points at the end of nine rounds wins the game.", "https://cf.geekdo-images.com/opengraph/img/TZVmfChYRrrBESKa3z9oMBlggRk=/fit-in/1200x630/pic4474567.jpg");
INSERT INTO `game` (`ID`, `name`, `minimum_number_of_players`, `maximum_number_of_players`, `suggested_age`, `average_playing_time`, `description`, `image_link`)
VALUES (5, "SURVIVE: ESCAPE FROM ATLANTIS", 2, 4, 8, 50, "The idea of the game is that you all control a group of inhabitants of the island of Atlantis, which is in the process of sinking in the water. ", "https://cf.geekdo-images.com/opengraph/img/yqc6wsSENdTGcbWj_Fwx9gxdJ1s=/fit-in/1200x630/pic1300182.png");
INSERT INTO `game` (`ID`, `name`, `minimum_number_of_players`, `maximum_number_of_players`, `suggested_age`, `average_playing_time`, `description`, `image_link`)
VALUES (6, "Gloomhaven (2017)", 1, 4, 12, 90, "Gloomhaven is a game of Euro-inspired tactical combat in a persistent world of shifting motives. Players will take on the role of a wandering adventurer with their own special set of skills and their own reasons for traveling to this dark corner of the world.", "https://cf.geekdo-images.com/itemrep/img/P7MVqNuhAl8Y4fxiM6e74kMX6e0=/fit-in/246x300/pic2437871.jpg");
INSERT INTO `game` (`ID`, `name`, `minimum_number_of_players`, `maximum_number_of_players`, `suggested_age`, `average_playing_time`, `description`, `image_link`)VALUES (7, "Terraforming Mars (2016)",1,5,12,120,"In the 2400s, mankind begins to terraform the planet Mars. Giant corporations, sponsored by the World Government on Earth, initiate huge projects to raise the temperature, the oxygen level, and the ocean coverage until the environment is habitable. In Terraforming Mars, you play one of those corporations and work together in the terraforming process, but compete for getting victory points that are awarded not only for your contribution to the terraforming, but also for advancing human infrastructure throughout the solar system, and doing other commendable things.
The players acquire unique project cards (from over two hundred different ones) by buying them to their hand. The projects (cards) can represent anything from introducing plant life or animals, hurling asteroids at the surface, building cities, to mining the moons of Jupiter and establishing greenhouse gas industries to heat up the atmosphere. The cards can give you immediate bonuses, as well as increasing your production of different resources. Many cards also have requirements and they become playable when the temperature, oxygen, or ocean coverage increases enough. Buying cards is costly, so there is a balance between buying cards (3 megacredits per card) and actually playing them (which can cost anything between 0 to 41 megacredits, depending on the project). Standard Projects are always available to complement your cards.
Your basic income, as well as your basic score, is based on your Terraform Rating (starting at 20), which increases every time you raise one of the three global parameters. However, your income is complemented with your production, and you also get VPs from many other sources.
Each player keeps track of their production and resources on their player boards, and the game uses six types of resources: MegaCredits, Steel, Titanium, Plants, Energy, and Heat. On the game board, you compete for the best places for your city tiles, ocean tiles, and greenery tiles. You also compete for different Milestones and Awards worth many VPs. Each round is called a generation (guess why) and consists of the following phases:
1) Player order shifts clockwise.
2) Research phase: All players buy cards from four privately drawn.
3) Action phase: Players take turns doing 1-2 actions from these options: Playing a card, claiming a Milestone, funding an Award, using a Standard project, converting plant into greenery tiles (and raising oxygen), converting heat into a temperature raise, and using the action of a card in play. The turn continues around the table (sometimes several laps) until all players have passed.
4) Production phase: Players get resources according to their terraform rating and production parameters.
When the three global parameters (temperature, oxygen, ocean) have all reached their goal, the terraforming is complete, and the game ends after that generation. Count your Terraform Rating and other VPs to determine the winning corporation!","https://cf.geekdo-images.com/itemrep/img/bhemoxL7PG1a_79L0D9syPTADSY=/fit-in/246x300/pic3536616.jpg");
INSERT INTO `game` (`ID`, `name`, `minimum_number_of_players`, `maximum_number_of_players`, `suggested_age`, `average_playing_time`, `description`, `image_link`)VALUES (8, "Brass: Birmingham (2018)",2,4,14,90, "Brass: Birmingham is an economic strategy game sequel to Martin Wallace 2007 masterpiece, Brass. Birmingham tells the story of competing entrepreneurs in Birmingham during the industrial revolution, between the years of 1770-1870.As in its predecessor, you must develop, build, and establish your industries and network, in an effort to exploit low or high market demands. Each round, players take turns according to the turn order track, receiving two actions to perform any of the following actions (found in the original game):
1) Build - Pay required resources and place an industry tile.
2) Network - Add a rail / canal link, expanding your network.
3) Develop - Increase the VP value of an industry.
4) Sell - Sell your cotton, manufactured goods and pottery.
5) Loan - Take a 30 loan and reduce your income.
Brass: Birmingham also features a new sixth action:
6) Scout - Discard three cards and take a wild location and wild industry card. (This action replaces Double Action Build in original Brass.)
The game is played over two halves: the canal era (years 1770-1830) and the rail era (years 1830-1870). To win the game, score the most VPs. VPs are counted at the end of each half for the canals, rails and established (flipped) industry tiles.
Birmingham features dynamic scoring canals/rails. Instead of each flipped industry tile giving a static 1 VP to all connected canals and rails, many industries give 0 or even 2 VPs. This provides players with the opportunity to score much higher value canals in the first era, and creates interesting strategy with industry placement.
Iron, coal, and cotton are three industries which appear in both the original Brass as well as in Brass: Birmingham.
New Sell system
Brewing has become a fundamental part of the culture in Birmingham. You must now sell your product through traders located around the edges of the board. Each of these traders is looking for a specific type of good each game. To sell cotton, pottery, or manufactured goods to these traders, you must also grease the wheels of industry by consuming beer. For example, a level 1 cotton mill requires one beer to flip. As an incentive to sell early, the first player to sell to a trader receives free beer.
Birmingham features three all-new industry types:
Brewery - Produces precious beer barrels required to sell goods.
Manufactured goods - Function like cotton, but features eight levels. Each level of manufactured goods provides unique rewards, rather than just escalating in VPs, making it a more versatile (yet potentially more difficult) path vs cotton.
Pottery - These behemoths of Birmingham offer huge VPs, but at a huge cost and need to plan.
Increased Coal and Iron Market size - The price of coal and iron can now go up to 8 per cube, and it s not uncommon.
Brass: Birmingham is a sequel to Brass. It offers a very different story arc and experience from its predecessor.","https://cf.geekdo-images.com/itemrep/img/_U34-eDDAf5K8Ftc9JDAi9vr-dE=/fit-in/246x300/pic3490053.jpg");
INSERT INTO `game` (`ID`, `name`, `minimum_number_of_players`, `maximum_number_of_players`, `suggested_age`, `average_playing_time`, `description`, `image_link`)VALUES (9, "Through the Ages: A New Story of Civilization (2015)",2,4,14,120,"Through the Ages: A New Story of Civilization is the new edition of Through the Ages: A Story of Civilization, with many changes small and large to the game's cards over its three ages and extensive changes to how military works.","https://cf.geekdo-images.com/itemrep/img/32e-PrFMZ0-P_KsnZHApZazlPqc=/fit-in/246x300/pic2663291.jpg");
INSERT INTO `game` (`ID`, `name`, `minimum_number_of_players`, `maximum_number_of_players`, `suggested_age`, `average_playing_time`, `description`, `image_link`)VALUES (10, "Twilight Imperium (Fourth Edition) (2017)",3,6,14,360,"Twilight Imperium (Fourth Edition) is a game of galactic conquest in which three to six players take on the role of one of seventeen factions vying for galactic domination through military might, political maneuvering, and economic bargaining.","https://cf.geekdo-images.com/itemrep/img/UxsyZBpFiBNPOppOQ7ILJde_YhY=/fit-in/246x300/pic3727516.jpg");
INSERT INTO `game` (`ID`, `name`, `minimum_number_of_players`, `maximum_number_of_players`, `suggested_age`, `average_playing_time`, `description`, `image_link`)VALUES (11, "Twilight Struggle (2005)",2,2,13,150,"Twilight Struggle inherits its fundamental s from the card-driven classics We the People and Hannibal: Rome vs. Carthage. It is a quick-playing, low-complexity game in that tradition. ","https://cf.geekdo-images.com/itemrep/img/0_gpX_v9CeKcm60nSkDzi47PVOA=/fit-in/246x300/pic361592.jpg");
INSERT INTO `game` (`ID`, `name`, `minimum_number_of_players`, `maximum_number_of_players`, `suggested_age`, `average_playing_time`, `description`, `image_link`)VALUES (12, "test",1,1,1,1,"Twilight Struggle inherits its fundamental s from the card-driven classics We the People and Hannibal: Rome vs. Carthage. It is a quick-playing, low-complexity game in that tradition. ","https://cf.geekdo-images.com/itemrep/img/0_gpX_v9CeKcm60nSkDzi47PVOA=/fit-in/246x300/pic361592.jpg");


